---
abstract: 'cron-like scheduler for Perl subroutines'
author:
  - 'Roland Huss (roland@cpan.org)'
build_requires:
  Test: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schedule-Cron
provides:
  Schedule::Cron:
    file: lib/Schedule/Cron.pm
    version: 1.02_3
requires:
  Data::Dumper: 0
  Time::ParseDate: 2011.0505
resources:
  bugtracker: https://github.com/rhuss/schedule-cron/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rhuss/schedule-cron.git
version: 1.02_3
